// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiklpdbczasjptskdbce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpa2xwZGJjemFzanB0c2tkYmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzM5NzAsImV4cCI6MjA2MzI0OTk3MH0.PUmbfcpwbsBjOcvyxuYZNUe5nHV2XpYV2J1y_F5HKrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);